baseURL = "https://yourdomain.com/"
languageCode = "zh-CN"
title = "我的博客123"
theme = "hugo-theme-cleanwhite"

[params]
  author = "您的姓名"
  description = "博客描述"
  github = "https://github.com/yourusername"
  email = "your.email@example.com"
  url = "https://yourdomain.com/"
  keywords = ["关键词1", "关键词2", "关键词3"]